### ISSUE TITLE
expose packer as lib

### ISSUE THREAD

**Issue by dr-bonez** [peku33/web-static-pack#6]
Would be good to be able to run the packer in a `build.rs` script.

**Comment by peku33** [comment]
I belive this is doable.
I don't know the exact use case, but making a pack should be integrated in pipeline that produces actual pack contents.
If you use webpack or something like that, this should be the last step after running the webpack, not first step of building the app.
The actual pack should be rebuilt when its contents are rebuilt, not on every application build/run.

**Comment by peku33** [comment]
Done https://github.com/peku33/web-static-pack/pull/7
